language: python
python: 2.7
env:
  - TARGET=test PLONE_VERSION=4.2
  - TARGET=test PLONE_VERSION=4.3
  - TARGET=coverage.sh PLONE_VERSION=4.3
  - TARGET=python-validation.sh PLONE_VERSION=4.3
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -N -q -t 5 -c travis.cfg install download install
  - bin/buildout -N -q -t 5 -c travis.cfg
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bin/$TARGET
